### ISSUE TITLE
Slow fixing over samba to Synology NAS

### ISSUE THREAD

**Issue by juan-fuentes-sis** [optyfr/JRomManager#187] opened 2023-02-12 11:00 UTC
I'm just guessing since both reads and writes are 7Mb/s on 1GB+ files that JRomManager is not buffering enough when using the java zip options.

Using the external zip application solves the issue.

I would like to suggest to enforce a bigger buffer for large files in java when reading/compressing to force larger reads/writes.

This is important as torrentzip is becoming the standard.

**Comment by optyfr** [comment] 2023-02-12 12:03
Samba is slow by design (compared to NFS or others) but... anyway, it's always preferable to scan/fix locally.
Since you are talking about external zip, I suppose you are using version 2.5.x? The Zip compression use another library in 3.0 (Zip4J is replacing ZipFileSystem), this may work faster, especially when adding/renaming/suppressing rom of existing zip files
Please give it a try, and tell me what you get, because if I have to fix something it will be in that version in any case

**Closed as completed** 2023-04-10 06:59 UTC
